# Hypothesis Testing

Hypothesis testing is one of statistical measures used to study relationship between variables.

We had to identify our rersearch questions from the objectives which will enable us achieve this test.

For this case we were interested in the relationship nbetween return on investment (ROI)and production budget.

In [1]:
import itertools
import numpy as np
import pandas as pd 
from numbers import Number
import sqlite3
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import f_oneway

import pickle
from fractions import Fraction

In [10]:
tn_movie_df = pd.read_csv('zippedData/tn.movie_budgets.csv.gz')
tn_movie_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [11]:
cols_to_clean = ['production_budget', 'domestic_gross', 'worldwide_gross']

for col in cols_to_clean:
    tn_movie_df[col] = tn_movie_df[col].replace('[\$,]', '', regex=True).astype(float)

In [12]:
tn_movie_df['worldwide_gross'] = pd.to_numeric(tn_movie_df['worldwide_gross'], errors='coerce')
tn_movie_df['production_budget'] = pd.to_numeric(tn_movie_df['production_budget'], errors='coerce')

In [13]:
tn_movie_df['ROI'] = (tn_movie_df['worldwide_gross'] - tn_movie_df['production_budget']) / tn_movie_df['production_budget']
tn_movie_df

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross,ROI
0,1,"Dec 18, 2009",Avatar,425000000.0,760507625.0,2.776345e+09,5.532577
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,410600000.0,241063875.0,1.045664e+09,1.546673
2,3,"Jun 7, 2019",Dark Phoenix,350000000.0,42762350.0,1.497624e+08,-0.572108
3,4,"May 1, 2015",Avengers: Age of Ultron,330600000.0,459005868.0,1.403014e+09,3.243841
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,317000000.0,620181382.0,1.316722e+09,3.153696
...,...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,7000.0,0.0,0.000000e+00,-1.000000
5778,79,"Apr 2, 1999",Following,6000.0,48482.0,2.404950e+05,39.082500
5779,80,"Jul 13, 2005",Return to the Land of Wonders,5000.0,1338.0,1.338000e+03,-0.732400
5780,81,"Sep 29, 2015",A Plague So Pleasant,1400.0,0.0,0.000000e+00,-1.000000
5781,82,"Aug 5, 2005",My Date With Drew,1100.0,181041.0,1.810410e+05,163.582727

### Hypothesis statement
Let 
𝜇
1
be the mean ROI of high-budget movies, and 
𝜇
2

be the mean ROI of low-budget movies.

Null Hypothesis (H₀):
𝜇
1
=
𝜇
2
There is no difference in mean ROI.

Alternative Hypothesis (H₁):
𝜇
1
≠
𝜇
2
There is a significant difference in mean ROI.

This is a two-tailed test.

Level of alpha = 0.05

### perform the test statistics

In [14]:
from scipy.stats import ttest_ind

# Define high and low budget threshold (e.g., median)
threshold = tn_movie_df['production_budget'].median()
high_budget = tn_movie_df[tn_movie_df['production_budget'] >= threshold]['ROI']cb
low_budget = tn_movie_df[tn_movie_df['production_budget'] < threshold]['ROI']

# Perform an independent t-test
t_stat, p_value = ttest_ind(high_budget, low_budget, equal_var=False)
p_value

3.555173979078268e-08

In [15]:
print("High Budget Mean ROI:", high_budget.mean())
print("Low Budget Mean ROI:", low_budget.mean())
print("p-value:", p_value)

High Budget Mean ROI: 1.6595916903497503
Low Budget Mean ROI: 5.978075243533361
p-value: 3.555173979078268e-08

### Decision rule

If 
𝑝
-value
<
𝛼
p-value<α: Reject H₀ → Evidence of significant difference

If 
𝑝
-value
≥
𝛼
p-value≥α: Fail to reject H₀ → No significant difference

### Conclusion

From the p-value 
3.555173979078268e-08
<
0.05  Therefore we reject H₀

Hence come into conclusion that there is a statistically significant difference in mean ROI between high- and low-budget movies.